In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("project_data.csv")

In [3]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel
...,...,...,...,...,...,...
887,Ta,Tara,zest,"3,10,000",NaN,NaN
888,Tata Zest XM Diesel,Tata,2018,"2,60,000","27,000 kms",Diesel
889,Mahindra Quanto C8,Mahindra,2013,"3,90,000","40,000 kms",Diesel
890,Honda Amaze 1.2 E i VTEC,Honda,2014,"1,80,000",Petrol,NaN
891,Chevrolet Sail 1.2 LT ABS,Chevrolet,2014,"1,60,000",Petrol,NaN

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    str
 1   company     892 non-null    str
 2   year        892 non-null    str
 3   Price       892 non-null    str
 4   kms_driven  840 non-null    str
 5   fuel_type   837 non-null    str
dtypes: str(6)
memory usage: 41.9 KB

In [5]:
# wrong datatype of year,price,kms_driven,type
#year can have wrong data
#price can involve wrong data
#kms_driven and fuel_type can have null values
#price and kms_driven can have commas

In [6]:
df.duplicated().value_counts()

False    798
True      94
Name: count, dtype: int64

In [7]:
df.drop_duplicates(inplace=True)

In [8]:
df.duplicated().value_counts()

False    798
Name: count, dtype: int64

In [9]:
#convert into numbers

df['year']= pd.to_numeric(df['year'],errors='coerce')

In [10]:
df['year'].unique()

array([2007., 2006., 2018., 2014., 2015., 2012., 2013., 2016., 2010.,
       2017., 2008., 2011., 2019., 2009., 2005., 2000.,   nan, 2003.,
       2004., 1995., 2002., 2001.])

In [11]:
#delete empty or null values
df.dropna(subset=['year'],inplace=True)

In [12]:
df['year'].unique()

array([2007., 2006., 2018., 2014., 2015., 2012., 2013., 2016., 2010.,
       2017., 2008., 2011., 2019., 2009., 2005., 2000., 2003., 2004.,
       1995., 2002., 2001.])

In [13]:
df.info()

<class 'pandas.DataFrame'>
Index: 749 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        749 non-null    str
 1   company     749 non-null    str
 2   year        749 non-null    float64
 3   Price       749 non-null    str
 4   kms_driven  748 non-null    str
 5   fuel_type   745 non-null    str
dtypes: float64(1), str(5)
memory usage: 41.0 KB

In [14]:
#Replace comma with blank

df['Price']=df['Price'].str.replace(",","")

In [15]:
df['Price']

0              80000
1             425000
2      Ask For Price
3             325000
4             575000
           ...
886           300000
888           260000
889           390000
890           180000
891           160000
Name: Price, Length: 749, dtype: str

In [16]:
#convert to numbers

df['Price']=pd.to_numeric(df['Price'],errors='coerce')

In [17]:
df['Price']

0       80000.0
1      425000.0
2           NaN
3      325000.0
4      575000.0
         ...
886    300000.0
888    260000.0
889    390000.0
890    180000.0
891    160000.0
Name: Price, Length: 749, dtype: float64

In [18]:
df.dropna(subset=['Price'],inplace=True)

In [19]:
df.info()

<class 'pandas.DataFrame'>
Index: 727 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        727 non-null    str
 1   company     727 non-null    str
 2   year        727 non-null    float64
 3   Price       727 non-null    float64
 4   kms_driven  727 non-null    str
 5   fuel_type   724 non-null    str
dtypes: float64(2), str(4)
memory usage: 39.8 KB

In [20]:
df['kms_driven']=df['kms_driven'].str.replace(",","")

In [21]:
df['kms_driven']

0       45000 kms
1          40 kms
3       28000 kms
4       36000 kms
6       41000 kms
          ...
886    132000 kms
888     27000 kms
889     40000 kms
890        Petrol
891        Petrol
Name: kms_driven, Length: 727, dtype: str

In [22]:
df['kms_driven']=df['kms_driven'].str.replace("kms","")

In [23]:
df['kms_driven']

0       45000
1          40
3       28000
4       36000
6       41000
        ...
886    132000
888     27000
889     40000
890     Petrol
891     Petrol
Name: kms_driven, Length: 727, dtype: str

In [24]:
df.info()

<class 'pandas.DataFrame'>
Index: 727 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        727 non-null    str
 1   company     727 non-null    str
 2   year        727 non-null    float64
 3   Price       727 non-null    float64
 4   kms_driven  727 non-null    str
 5   fuel_type   724 non-null    str
dtypes: float64(2), str(4)
memory usage: 39.8 KB

In [25]:
df['kms_driven']=pd.to_numeric(df['kms_driven'],errors='coerce')

In [26]:
df.dropna(subset=['kms_driven'],inplace=True)

In [27]:
df['kms_driven']

0       45000.0
1          40.0
3       28000.0
4       36000.0
6       41000.0
         ...
883     50000.0
885     30000.0
886    132000.0
888     27000.0
889     40000.0
Name: kms_driven, Length: 725, dtype: float64

In [28]:
df.info()

<class 'pandas.DataFrame'>
Index: 725 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        725 non-null    str
 1   company     725 non-null    str
 2   year        725 non-null    float64
 3   Price       725 non-null    float64
 4   kms_driven  725 non-null    float64
 5   fuel_type   724 non-null    str
dtypes: float64(3), str(3)
memory usage: 39.6 KB

In [29]:
df['fuel_type'].unique()

<StringArray>
['Petrol', 'Diesel', nan, 'LPG']
Length: 4, dtype: str

In [30]:
df.dropna(subset=['fuel_type'],inplace=True)

In [31]:
df['fuel_type'].unique()

<StringArray>
['Petrol', 'Diesel', 'LPG']
Length: 3, dtype: str

In [32]:
df.info()

<class 'pandas.DataFrame'>
Index: 724 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        724 non-null    str
 1   company     724 non-null    str
 2   year        724 non-null    float64
 3   Price       724 non-null    float64
 4   kms_driven  724 non-null    float64
 5   fuel_type   724 non-null    str
dtypes: float64(3), str(3)
memory usage: 39.6 KB

In [33]:
df['company'].unique()

<StringArray>
[   'Hyundai',   'Mahindra',       'Ford',     'Maruti',      'Skoda',
       'Audi',     'Toyota',    'Renault',      'Honda',     'Datsun',
 'Mitsubishi',       'Tata', 'Volkswagen',  'Chevrolet',       'Mini',
        'BMW',     'Nissan',  'Hindustan',       'Fiat',      'Force',
   'Mercedes',       'Land',     'Jaguar',       'Jeep',      'Volvo']
Length: 25, dtype: str

In [34]:
df['name'].unique()

<StringArray>
[  'Hyundai Santro Xing XO eRLX Euro III',
                'Mahindra Jeep CL550 MDI',
 'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi',
                              'Ford Figo',
                            'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
         'Maruti Suzuki Alto K10 VXi AMT',
            'Skoda Fabia Classic 1.2 MPI',
             'Maruti Suzuki Stingray VXi',
 ...
                     'Mahindra Quanto C4',
              'Maruti Suzuki Swift Dzire',
             'Hyundai i20 Select Variant',
                   'Honda City VX Petrol',
                           'Hyundai Getz',
         'Mercedes Benz C Class 200 K MT',
                            'Skoda Fabia',
             'Maruti Suzuki Ritz VXI ABS',
              'Tata Indica V2 DLE BS III',
                    'Tata Zest XM Diesel']
Length: 463, dtype: str

In [35]:
#Removes the company name from the name

for i in df.index:
    company= df.loc[i,"company"]
    name=df.loc[i,"name"]
    name=name.replace(company,"").strip()
    df.loc[i,"name"]=name

In [36]:
df['name']

0        Santro Xing XO eRLX Euro III
1                      Jeep CL550 MDI
3      Grand i10 Magna 1.2 Kappa VTVT
4         EcoSport Titanium 1.5L TDCi
6                                Figo
                    ...
883               Suzuki Ritz VXI ABS
885              Indica V2 DLE BS III
886                     Corolla Altis
888                    Zest XM Diesel
889                         Quanto C8
Name: name, Length: 724, dtype: str

In [37]:
df['year'].unique()

array([2007., 2006., 2014., 2012., 2013., 2016., 2015., 2010., 2017.,
       2008., 2018., 2011., 2019., 2009., 2005., 2000., 2003., 2004.,
       1995., 2002., 2001.])

In [38]:
df['Price'].unique().sort()

In [39]:
df['Price']

0       80000.0
1      425000.0
3      325000.0
4      575000.0
6      175000.0
         ...
883    270000.0
885    110000.0
886    300000.0
888    260000.0
889    390000.0
Name: Price, Length: 724, dtype: float64

In [40]:
df['Price'].min()

np.float64(30000.0)

In [41]:
#keep only those rows where the price column is greater than 100000.


df=(df[df['Price']>100000])

In [42]:
df

,name,company,year,Price,kms_driven,fuel_type
1,Jeep CL550 MDI,Mahindra,2006.0,425000.0,40.0,Diesel
3,Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014.0,325000.0,28000.0,Petrol
4,EcoSport Titanium 1.5L TDCi,Ford,2014.0,575000.0,36000.0,Diesel
6,Figo,Ford,2012.0,175000.0,41000.0,Diesel
7,Eon,Hyundai,2013.0,190000.0,25000.0,Petrol
...,...,...,...,...,...,...
883,Suzuki Ritz VXI ABS,Maruti,2011.0,270000.0,50000.0,Petrol
885,Indica V2 DLE BS III,Tata,2009.0,110000.0,30000.0,Diesel
886,Corolla Altis,Toyota,2009.0,300000.0,132000.0,Petrol
888,Zest XM Diesel,Tata,2018.0,260000.0,27000.0,Diesel
889,Quanto C8,Mahindra,2013.0,390000.0,40000.0,Diesel

In [43]:
df['Price'].max()

np.float64(8500003.0)

In [44]:


df[df['Price']>=df['Price'].max()]

          name   company    year      Price  kms_driven fuel_type
562  XUV500 W6  Mahindra  2014.0  8500003.0     45000.0    Diesel

In [45]:
#keep only those rows where the Price column is less than 8500000.


df= df[df['Price']<8500000]

In [46]:
df['Price']

1      425000.0
3      325000.0
4      575000.0
6      175000.0
7      190000.0
         ...
883    270000.0
885    110000.0
886    300000.0
888    260000.0
889    390000.0
Name: Price, Length: 635, dtype: float64

In [47]:
df['Price'].min()

np.float64(105000.0)

In [48]:
#keep only those rows where the kms_driven column is greater than 1000.


df = df[df['kms_driven']>1000]

In [49]:
df.info()

<class 'pandas.DataFrame'>
Index: 618 entries, 3 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        618 non-null    str
 1   company     618 non-null    str
 2   year        618 non-null    float64
 3   Price       618 non-null    float64
 4   kms_driven  618 non-null    float64
 5   fuel_type   618 non-null    str
dtypes: float64(3), str(3)
memory usage: 33.8 KB

In [50]:
df.reset_index(drop=True,inplace= True)

In [51]:
df

,name,company,year,Price,kms_driven,fuel_type
0,Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014.0,325000.0,28000.0,Petrol
1,EcoSport Titanium 1.5L TDCi,Ford,2014.0,575000.0,36000.0,Diesel
2,Figo,Ford,2012.0,175000.0,41000.0,Diesel
3,Eon,Hyundai,2013.0,190000.0,25000.0,Petrol
4,EcoSport Ambiente 1.5L TDCi,Ford,2016.0,830000.0,24530.0,Diesel
...,...,...,...,...,...,...
613,Suzuki Ritz VXI ABS,Maruti,2011.0,270000.0,50000.0,Petrol
614,Indica V2 DLE BS III,Tata,2009.0,110000.0,30000.0,Diesel
615,Corolla Altis,Toyota,2009.0,300000.0,132000.0,Petrol
616,Zest XM Diesel,Tata,2018.0,260000.0,27000.0,Diesel
617,Quanto C8,Mahindra,2013.0,390000.0,40000.0,Diesel

In [52]:
#keep only those rows where the year column is greater than 2000.

df = df[df['year']>2000]

In [53]:
df.info()

<class 'pandas.DataFrame'>
Index: 617 entries, 0 to 617
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        617 non-null    str
 1   company     617 non-null    str
 2   year        617 non-null    float64
 3   Price       617 non-null    float64
 4   kms_driven  617 non-null    float64
 5   fuel_type   617 non-null    str
dtypes: float64(3), str(3)
memory usage: 33.7 KB

In [54]:
df.to_csv("cleaned_CarPrediction.csv", index=False)